<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelProduct</name>
   <tag></tag>
   <elementGuidId>e5c87205-748c-4d72-b125-349db8003b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Products')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Products')]</value>
      <webElementGuid>f2a2e06c-c8b4-4bfb-aa08-882fcb621c31</webElementGuid>
   </webElementProperties>
</WebElementEntity>
